// Generated by gencpp from file metrics_refbox_msgs/ActivityRecognitionResult.msg
// DO NOT EDIT!


#ifndef METRICS_REFBOX_MSGS_MESSAGE_ACTIVITYRECOGNITIONRESULT_H
#define METRICS_REFBOX_MSGS_MESSAGE_ACTIVITYRECOGNITIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace metrics_refbox_msgs
{
template <class ContainerAllocator>
struct ActivityRecognitionResult_
{
  typedef ActivityRecognitionResult_<ContainerAllocator> Type;

  ActivityRecognitionResult_()
    : message_type(0)
    , activities()  {
    }
  ActivityRecognitionResult_(const ContainerAllocator& _alloc)
    : message_type(0)
    , activities(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _message_type_type;
  _message_type_type message_type;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _activities_type;
  _activities_type activities;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FEEDBACK)
  #undef FEEDBACK
#endif
#if defined(_WIN32) && defined(RESULT)
  #undef RESULT
#endif

  enum {
    FEEDBACK = 1u,
    RESULT = 2u,
  };


  typedef boost::shared_ptr< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> const> ConstPtr;

}; // struct ActivityRecognitionResult_

typedef ::metrics_refbox_msgs::ActivityRecognitionResult_<std::allocator<void> > ActivityRecognitionResult;

typedef boost::shared_ptr< ::metrics_refbox_msgs::ActivityRecognitionResult > ActivityRecognitionResultPtr;
typedef boost::shared_ptr< ::metrics_refbox_msgs::ActivityRecognitionResult const> ActivityRecognitionResultConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator1> & lhs, const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator2> & rhs)
{
  return lhs.message_type == rhs.message_type &&
    lhs.activities == rhs.activities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator1> & lhs, const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace metrics_refbox_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be6bf821856377e457fb3a0315d48f81";
  }

  static const char* value(const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe6bf821856377e4ULL;
  static const uint64_t static_value2 = 0x57fb3a0315d48f81ULL;
};

template<class ContainerAllocator>
struct DataType< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "metrics_refbox_msgs/ActivityRecognitionResult";
  }

  static const char* value(const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 FEEDBACK=1\n"
"uint8 RESULT=2\n"
"uint8 message_type\n"
"# list of activities ordered from most probable to least probable.\n"
"# Up to a maximum of 5 activities will be considered for evaluation\n"
"string[] activities\n"
;
  }

  static const char* value(const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message_type);
      stream.next(m.activities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivityRecognitionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::metrics_refbox_msgs::ActivityRecognitionResult_<ContainerAllocator>& v)
  {
    s << indent << "message_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.message_type);
    s << indent << "activities[]" << std::endl;
    for (size_t i = 0; i < v.activities.size(); ++i)
    {
      s << indent << "  activities[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.activities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // METRICS_REFBOX_MSGS_MESSAGE_ACTIVITYRECOGNITIONRESULT_H
