// Generated by gencpp from file metrics_refbox_msgs/AssessActivityStateResult.msg
// DO NOT EDIT!


#ifndef METRICS_REFBOX_MSGS_MESSAGE_ASSESSACTIVITYSTATERESULT_H
#define METRICS_REFBOX_MSGS_MESSAGE_ASSESSACTIVITYSTATERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <metrics_refbox_msgs/BoundingBox2D.h>

namespace metrics_refbox_msgs
{
template <class ContainerAllocator>
struct AssessActivityStateResult_
{
  typedef AssessActivityStateResult_<ContainerAllocator> Type;

  AssessActivityStateResult_()
    : message_type(0)
    , phase(0)
    , image()
    , box2d()
    , activities()  {
    }
  AssessActivityStateResult_(const ContainerAllocator& _alloc)
    : message_type(0)
    , phase(0)
    , image(_alloc)
    , box2d(_alloc)
    , activities(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _message_type_type;
  _message_type_type message_type;

   typedef uint8_t _phase_type;
  _phase_type phase;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::metrics_refbox_msgs::BoundingBox2D_<ContainerAllocator>  _box2d_type;
  _box2d_type box2d;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _activities_type;
  _activities_type activities;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FEEDBACK)
  #undef FEEDBACK
#endif
#if defined(_WIN32) && defined(RESULT)
  #undef RESULT
#endif
#if defined(_WIN32) && defined(PHASE_DETECTION)
  #undef PHASE_DETECTION
#endif
#if defined(_WIN32) && defined(PHASE_VISUAL_ASSESSMENT)
  #undef PHASE_VISUAL_ASSESSMENT
#endif
#if defined(_WIN32) && defined(PHASE_VERBAL_ASSESSMENT)
  #undef PHASE_VERBAL_ASSESSMENT
#endif

  enum {
    FEEDBACK = 1u,
    RESULT = 2u,
    PHASE_DETECTION = 1u,
    PHASE_VISUAL_ASSESSMENT = 2u,
    PHASE_VERBAL_ASSESSMENT = 3u,
  };


  typedef boost::shared_ptr< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> const> ConstPtr;

}; // struct AssessActivityStateResult_

typedef ::metrics_refbox_msgs::AssessActivityStateResult_<std::allocator<void> > AssessActivityStateResult;

typedef boost::shared_ptr< ::metrics_refbox_msgs::AssessActivityStateResult > AssessActivityStateResultPtr;
typedef boost::shared_ptr< ::metrics_refbox_msgs::AssessActivityStateResult const> AssessActivityStateResultConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator1> & lhs, const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator2> & rhs)
{
  return lhs.message_type == rhs.message_type &&
    lhs.phase == rhs.phase &&
    lhs.image == rhs.image &&
    lhs.box2d == rhs.box2d &&
    lhs.activities == rhs.activities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator1> & lhs, const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace metrics_refbox_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "158623e93d31a5f8e12464016a13faf0";
  }

  static const char* value(const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x158623e93d31a5f8ULL;
  static const uint64_t static_value2 = 0xe12464016a13faf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "metrics_refbox_msgs/AssessActivityStateResult";
  }

  static const char* value(const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 FEEDBACK=1\n"
"uint8 RESULT=2\n"
"uint8 message_type\n"
"\n"
"# feedback\n"
"uint8 PHASE_DETECTION=1\n"
"uint8 PHASE_VISUAL_ASSESSMENT=2\n"
"uint8 PHASE_VERBAL_ASSESSMENT=3\n"
"\n"
"uint8 phase\n"
"\n"
"# phase: detection\n"
"sensor_msgs/Image image\n"
"BoundingBox2D box2d\n"
"\n"
"# for all of the following phases/result\n"
"# we need to return a list of activities:\n"
"#\n"
"# phase: visual assessment\n"
"# phase: verbal assessment\n"
"# final result\n"
"\n"
"# list of activities ordered from most probable to least probable.\n"
"# Up to a maximum of 5 activities will be considered for evaluation\n"
"string[] activities\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: metrics_refbox_msgs/BoundingBox2D\n"
"uint32 min_x\n"
"uint32 min_y\n"
"uint32 max_x\n"
"uint32 max_y\n"
;
  }

  static const char* value(const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message_type);
      stream.next(m.phase);
      stream.next(m.image);
      stream.next(m.box2d);
      stream.next(m.activities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssessActivityStateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::metrics_refbox_msgs::AssessActivityStateResult_<ContainerAllocator>& v)
  {
    s << indent << "message_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.message_type);
    s << indent << "phase: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.phase);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "box2d: ";
    s << std::endl;
    Printer< ::metrics_refbox_msgs::BoundingBox2D_<ContainerAllocator> >::stream(s, indent + "  ", v.box2d);
    s << indent << "activities[]" << std::endl;
    for (size_t i = 0; i < v.activities.size(); ++i)
    {
      s << indent << "  activities[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.activities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // METRICS_REFBOX_MSGS_MESSAGE_ASSESSACTIVITYSTATERESULT_H
