// Generated by gencpp from file metrics_refbox_msgs/PersonDetectionResult.msg
// DO NOT EDIT!


#ifndef METRICS_REFBOX_MSGS_MESSAGE_PERSONDETECTIONRESULT_H
#define METRICS_REFBOX_MSGS_MESSAGE_PERSONDETECTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <metrics_refbox_msgs/BoundingBox2D.h>
#include <sensor_msgs/Image.h>

namespace metrics_refbox_msgs
{
template <class ContainerAllocator>
struct PersonDetectionResult_
{
  typedef PersonDetectionResult_<ContainerAllocator> Type;

  PersonDetectionResult_()
    : message_type(0)
    , person_found(false)
    , box2d()
    , image()  {
    }
  PersonDetectionResult_(const ContainerAllocator& _alloc)
    : message_type(0)
    , person_found(false)
    , box2d(_alloc)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _message_type_type;
  _message_type_type message_type;

   typedef uint8_t _person_found_type;
  _person_found_type person_found;

   typedef  ::metrics_refbox_msgs::BoundingBox2D_<ContainerAllocator>  _box2d_type;
  _box2d_type box2d;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FEEDBACK)
  #undef FEEDBACK
#endif
#if defined(_WIN32) && defined(RESULT)
  #undef RESULT
#endif

  enum {
    FEEDBACK = 1u,
    RESULT = 2u,
  };


  typedef boost::shared_ptr< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> const> ConstPtr;

}; // struct PersonDetectionResult_

typedef ::metrics_refbox_msgs::PersonDetectionResult_<std::allocator<void> > PersonDetectionResult;

typedef boost::shared_ptr< ::metrics_refbox_msgs::PersonDetectionResult > PersonDetectionResultPtr;
typedef boost::shared_ptr< ::metrics_refbox_msgs::PersonDetectionResult const> PersonDetectionResultConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator1> & lhs, const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator2> & rhs)
{
  return lhs.message_type == rhs.message_type &&
    lhs.person_found == rhs.person_found &&
    lhs.box2d == rhs.box2d &&
    lhs.image == rhs.image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator1> & lhs, const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace metrics_refbox_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9dd3e562d32c962b7c2882022afa06a";
  }

  static const char* value(const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9dd3e562d32c962ULL;
  static const uint64_t static_value2 = 0xb7c2882022afa06aULL;
};

template<class ContainerAllocator>
struct DataType< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "metrics_refbox_msgs/PersonDetectionResult";
  }

  static const char* value(const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 FEEDBACK=1\n"
"uint8 RESULT=2\n"
"uint8 message_type\n"
"\n"
"# set to true if a person has been found\n"
"bool person_found\n"
"\n"
"# 2D bounding box of the person\n"
"BoundingBox2D box2d\n"
"\n"
"# image which contains the person (corresponding to the 2D bounding box)\n"
"sensor_msgs/Image image\n"
"\n"
"================================================================================\n"
"MSG: metrics_refbox_msgs/BoundingBox2D\n"
"uint32 min_x\n"
"uint32 min_y\n"
"uint32 max_x\n"
"uint32 max_y\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message_type);
      stream.next(m.person_found);
      stream.next(m.box2d);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonDetectionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::metrics_refbox_msgs::PersonDetectionResult_<ContainerAllocator>& v)
  {
    s << indent << "message_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.message_type);
    s << indent << "person_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.person_found);
    s << indent << "box2d: ";
    s << std::endl;
    Printer< ::metrics_refbox_msgs::BoundingBox2D_<ContainerAllocator> >::stream(s, indent + "  ", v.box2d);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // METRICS_REFBOX_MSGS_MESSAGE_PERSONDETECTIONRESULT_H
