FROM ros:noetic-robot
ARG USERNAME
ARG USER_UID=1000
ARG USER_GID=$USER_UID

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip git \
    && pip install -U wstool
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -ms "/bin/bash" $USERNAME \
    && apt-get install -y --no-install-recommends sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN echo "yaml file:///workspaces/robonotts_ws/rosdeps.yaml" > /etc/ros/rosdep/sources.list.d/10-robonotts.list

USER $USERNAME

ADD init_shell.sh /home/$USERNAME/init_shell.sh

RUN echo ". /ros_entrypoint.sh" >> ~/.bashrc
RUN echo "set +e" >> ~/.bashrc